version: "3"

services:
  auth-service:
    build: ./university-management-auth-service
    ports:
      - "3001:3001"
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis

  core-service:
    build: ./university-management-core-service
    ports:
      - "3002:3002"
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis

  api-gateway:
    build: ./university-management-api-gateway
    ports:
      - "3003:3003"
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
