version: "3"

services:
  auth-service:
    image: 0nahid/auth-service:latest 
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  core-service:
    image: 0nahid/core-service:latest
    ports:
      - "3002:3002"

  api-gateway:
    image: 0nahid/api-gateway:latest
    ports:
      - "3003:3003"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
