name: Build and Push to DockerHub

on:
  push:
    branches:
      - main # Trigger the workflow on push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push auth-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./university-management-auth-service
          push: true
          tags: 0nahid/auth-service:latest # Replace with your Docker Hub username

      - name: Build and push core-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./university-management-core-service
          push: true
          tags: 0nahid/core-service:latest # Replace with your Docker Hub username

      - name: Build and push api-gateway Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./university-management-api-gateway
          push: true
          tags: 0nahid/api-gateway:latest # Replace with your Docker Hub username
